# Generated by Django 2.0.5 on 2018-05-30 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{3}-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números y los símbolos: + -')])),
                ('telefono_casa', models.CharField(help_text='Número telefónico de contacto con el usuario', max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{3}-\\d{3}-\\d{7}$', 'Número telefónico inválido. Solo se permiten números y los símbolos: + -')])),
                ('correo', models.CharField(help_text='correo@correo.com', max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^[VE][\\d]{8}$', 'Introduzca un número de cédula válido. Solo se permiten números y una longitud de 8 carácteres. Se agrega un 0 si la longitud es de 7 carácteres.')])),
            ],
        ),
    ]
